-- M9.5: Activities Builder feature + internship preset
--
-- Extends input_kind to include 'builder' (resumes generated by the AI builder).
-- Adds is_internship preset flag (target student/new-grad calibration).
-- Adds builder_input (jsonb of the structured form the user submitted) and
-- builder_rewrites_used (per-draft cap on targeted bullet rewrites).

alter table resumes
  drop constraint if exists resumes_input_kind_check;

alter table resumes
  add constraint resumes_input_kind_check
    check (input_kind in ('pdf', 'url', 'image', 'builder'));

alter table resumes
  add column if not exists is_internship boolean not null default false,
  add column if not exists builder_input jsonb,
  add column if not exists builder_rewrites_used integer not null default 0;
